### ISSUE TITLE
Which board for a daisy seed ?

### ISSUE THREAD

**Issue by phil123456** [electro-smith/pd2dsy#28] opened 2023-03-13 15:00 UTC
Hi,

I tried to generate a code for a Daisy Seed but I get an error

```
$ python pd2dsy.py --board patch examples/PdFiles/saw_test.pd
Generating project in ".\saw_test"
  1) Error c2daisy: Unknown parameter "ChannelA"
(pd_env)
```

Win 10 home edition
$ git log --oneline
d20c6ba (HEAD -> master, origin/master, origin/HEAD) consistency in commands for venv activation

**Comment by takumi-ogata** [comment] 2023-04-12 20:30
Hi Phil, 

I'm sorry for the delay in response. 

Regarding your inquiry about "Which board for a daisy seed ?", we currently don't have a built-in seed board (like with Patch, Pod, and etc) since seed doesn't have a fixed interface. 

That being said, we totally understand the need for having a vanilla seed option that's only for audio processing to test things out. So just for using [adc~] and [dac~] and no other Daisy I/Os. [plugdata](https://plugdata.org/) (which I recommend) has such option.   

In the meantime, if you're just working with audio, you can arbitrary just use `--board pod` for example. But be careful to not run an example patch that was designed for a specific board in mind (or vice versa in your case where you ran a Pure Data patch that wasn't made for Daisy Patch).    

And once you are ready to connect components such as potentiometer, you can use a custom JSON file which you can learn about in: https://github.com/electro-smith/DaisyWiki/wiki/Pd2dsy-JSON 
There forum posts with helpful tips as well. 

By the way, Phil, we highly recommend that you use the forum. If questions and issues you bring up on there should be opened up on GitHub, we can do it for you. We often see forum-type questions ending up here on GitHub and we really want to keep it separated. Thank you and I'll see you in the forum!!

**Closed by takumi-ogata** 2023-04-12 20:30 UTC
